#lang setup/infotab
(define name "uuid-v4")
(define blurb '((p "uuid-v4 lets you make v4 uuid's quickly.")))
(define release-notes '((p "This is a major port that is now compatible with PLT 5.0. It also includes new documentation ")))
(define primary-file "uuid-v4.rkt")
(define required-core-version "4.1")
(define repositories '("4.x"))
(define categories '(devtools))
(define version "0.4")
(define scribblings '(("manual.scrbl" ())))